### ISSUE TITLE
some packages cannot installed

### ISSUE THREAD

**Issue by vptgeg** [sans-dfir/sift-bootstrap#17]
hi,

when i run 
curl --silent -L https://raw.github.com/sans-dfir/sift-bootstrap/master/bootstrap.sh | sudo bash -s -- -i

or the wget equivalent three packages are not able to install

dff
4n6time static
guymager

all packages seems to stuck on dependencies:
The following packages have unmet dependencies:
 guymager : Depends: libewf2 (>= 20121209)
E: Unable to correct problems, you have held broken packages.

best

**Comment by philhagen** [comment]
Plain vanilla 14.04 install with updates as of 2015-01-10.  Received following errors in bootstrap:
 * ERROR: Install Failure: 4n6time-static (Error Code: 100)
 * ERROR: Install Failure: dff (Error Code: 100)
 * ERROR: Install Failure: guymager (Error Code: 100)

During the post-install script, seven of the following errors were displayed (three for each of two PIDs, one for a third PID):
(process:<%PID%>): dconf-CRITICAL **: unable to create file '/home/user/.cache/dconf/user': Permission denied.  dconf will not work properly.

No other package management utilities running at the time.

**Comment by ekristen** [comment]
Those packages have been removed. I'm opening a new issue for the dconf errors
