### ISSUE TITLE
Usage of deprecated HAL leads to boot warnings 

### ISSUE THREAD

**Issue by pklanka** [sans-dfir/sift-bootstrap#23]
Usage of HAL http://en.wikipedia.org/wiki/HAL_(software) is deprecated and leads to multiple warnings during bootup of the latest Ubuntu 14.04. I think it is best to migrate to udev which offers exactly similar functionality.

Here is the sample error received during bootup - this text repeats some 50 times.
*failed to execute '/lib/udev/socket:@/org/freedesktop/hal/udev_event' 'socket:@/org/freedesktop/hal/udev_event': No such file or directory*

**Comment by ekristen** [comment]
Any idea what is using HAL? To throw theses warnings?

**Comment by pklanka** [comment]
I think these warnings are more so with the installation of hal and
hal-info packages rather than what are they being used with. On a fresh
Ubuntu 14.04 installing only hal leads to the same set of errors. More so
than ever the question should be if there are any downward dependencies
that require hal and hal-info to be installed. Otherwise, we would be
better off removing these packages from the script. I believe Ubuntu is in
the process of deprecating hal altogether. So from a dependency perspective
there is a quite minimal chance that other packages would need hal to be
installed.

cheers
Phani

**Comment by ekristen** [comment]
I removed it in development and haven't seen any problems so far. Plan to comit to master soon

**Comment by ekristen** [comment]
This should be fixed soon, its in dev.
